name: compile-test-deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven

      - name: build with maven
        run: mvn -B package

      - name: log in to docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: build and push Docker image
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            image_tag=$(git log -1 --pretty=%h)
            docker build -t ${{ secrets.DOCKER_USERNAME }}/elecedb:$image_tag -t ${{ secrets.DOCKER_USERNAME }}/elecedb:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/elecedb:$image_tag
            docker push ${{ secrets.DOCKER_USERNAME }}/elecedb:latest
          else
            echo "Skipping Docker image build on pull requests."
          fi